server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cdnqudsux9ie.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-junho?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            clientId: 653465623795-dg7e7gbg8t2t8gk146kb40esn9gq3i6j.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: 28eCTeQzcidq8sTh2gTO
            clientSecret: Z77tbw7iXF
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\junil\junho\web\springboot\stussy-clone-20220929-junho/upload/