server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cdnqudsux9ie.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-junho?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            clientId: 653465623795-dg7e7gbg8t2t8gk146kb40esn9gq3i6j.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\junil\junho\web\springboot\stussy-clone-20220929-junho/upload/